# Generated by Django 5.2 on 2026-03-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('bot_token', models.CharField(help_text='Токен бота от @BotFather', max_length=255, verbose_name='Bot Token')),
                ('chat_id', models.CharField(help_text='ID группы или канала для уведомлений', max_length=255, verbose_name='Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Telegram Notification Settings',
                'verbose_name_plural': 'Telegram Notification Settings',
            },
        ),
    ]
