# Generated by Django 5.2 on 2026-03-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotificationsettings',
            name='alerts_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для алертов и отказов (message_thread_id из Telegram update)', max_length=100, verbose_name='Alerts Thread ID'),
        ),
        migrations.AddField(
            model_name='telegramnotificationsettings',
            name='cleaner_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для событий клинеров (message_thread_id из Telegram update)', max_length=100, verbose_name='Cleaner Thread ID'),
        ),
        migrations.AddField(
            model_name='telegramnotificationsettings',
            name='completed_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для завершённых заказов (message_thread_id из Telegram update)', max_length=100, verbose_name='Completed Orders Thread ID'),
        ),
        migrations.AddField(
            model_name='telegramnotificationsettings',
            name='expenses_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для расходов (message_thread_id из Telegram update)', max_length=100, verbose_name='Expenses Thread ID'),
        ),
        migrations.AddField(
            model_name='telegramnotificationsettings',
            name='orders_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для заказов (message_thread_id из Telegram update)', max_length=100, verbose_name='Orders Thread ID'),
        ),
    ]
