# Generated by Django 5.2 on 2026-03-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_telegramnotificationsettings_alerts_thread_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramnotificationsettings',
            options={'verbose_name': 'Настройки Telegram уведомлений', 'verbose_name_plural': 'Настройки Telegram уведомлений'},
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='alerts_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для алертов и отказов (message_thread_id из Telegram update)', max_length=100, verbose_name='ID темы алертов'),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='bot_token',
            field=models.CharField(help_text='Токен бота от @BotFather', max_length=255, verbose_name='Токен бота'),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='chat_id',
            field=models.CharField(help_text='ID группы или канала для уведомлений', max_length=255, verbose_name='ID группы'),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='cleaner_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для событий клинеров (message_thread_id из Telegram update)', max_length=100, verbose_name='ID темы событий клинеров'),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='completed_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для завершённых заказов (message_thread_id из Telegram update)', max_length=100, verbose_name='ID темы завершённых заказов'),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='expenses_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для расходов (message_thread_id из Telegram update)', max_length=100, verbose_name='ID темы расходов'),
        ),
        migrations.AlterField(
            model_name='telegramnotificationsettings',
            name='orders_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для заказов (message_thread_id из Telegram update)', max_length=100, verbose_name='ID темы заказов'),
        ),
    ]
