# Generated by Django 5.2 on 2026-03-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_telegramnotificationsettings_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramNotificationSettings',
        ),
    ]
