# Generated by Django 5.2 on 2025-09-17 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_alter_user_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Введите номер в формате +996558000350 или 996558000350', max_length=100, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате +996xxxxxxxxx или 996xxxxxxxxx', regex='^(\\+996\\d{9}|996\\d{9})$')], verbose_name='WhatsApp'),
        ),
    ]
