# Generated by Django 5.2 on 2025-09-25 11:55

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата найма'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_back',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='users_passports/', verbose_name='Фото паспорта (обратная сторона)'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_front',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='users_passports/', verbose_name='Фото паспорта (лицевая сторона)'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_type',
            field=models.CharField(choices=[('HOURLY', 'Почасовая оплата'), ('PER_ORDER', 'Оплата за заказ'), ('FIXED', 'Фиксированная ставка'), ('MIXED', 'Смешанный формат')], default='HOURLY', max_length=50, verbose_name='Формат оплаты'),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ставка'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активен'), ('CANDIDATE', 'Кандидат'), ('FIRED', 'Уволен')], default='CANDIDATE', max_length=50, verbose_name='Статус сотрудника'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='users_avatars/', verbose_name='Фото'),
        ),
    ]
