# Generated by Django 5.2 on 2025-10-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_hire_date_user_passport_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Свободен'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_on_shift',
            field=models.BooleanField(default=False, verbose_name='На смене'),
        ),
    ]
