# Generated by Django 5.2 on 2025-12-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_available_user_is_on_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_on_shift',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('IT', 'IT Отдел'), ('FOUNDER', 'Основатель'), ('SMM', 'СММ-менеджер'), ('OPERATOR', 'Оператор'), ('MANAGER', 'Менеджер'), ('CANDIDATE', 'Кандидат')], default='CANDIDATE', max_length=50, verbose_name='Роль'),
        ),
    ]
