# Generated by Django 5.2 on 2025-12-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_available_remove_user_is_on_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('IT', 'IT Отдел'), ('FOUNDER', 'Основатель'), ('SMM', 'СММ-менеджер'), ('OPERATOR', 'Оператор'), ('MANAGER', 'Менеджер'), ('SENIOR_CLEANER', 'Старший клинер'), ('CLEANER', 'Клинер'), ('CANDIDATE', 'Кандидат')], default='CANDIDATE', max_length=50, verbose_name='Роль'),
        ),
    ]
