# Generated by Django 5.2 on 2026-03-09 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(db_index=True, help_text='Основной телефон для входа (формат: +996XXXXXXXXX)', max_length=20, unique=True, verbose_name='Телефон')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Полное имя')),
                ('role', models.CharField(choices=[('FOUNDER', 'Основатель'), ('MANAGER', 'Менеджер'), ('OPERATOR', 'Оператор'), ('SMM', 'SMM'), ('HR', 'HR'), ('SENIOR_CLEANER', 'Старший клинер'), ('CLEANER', 'Клинер')], db_index=True, default='CLEANER', max_length=20, verbose_name='Роль')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет, может ли пользователь входить в админ-панель.', verbose_name='Статус персонала')),
                ('is_active', models.BooleanField(default=True, help_text='Определяет, активна ли учетная запись.', verbose_name='Активен')),
                ('is_superuser', models.BooleanField(default=False, help_text='Определяет, имеет ли пользователь все разрешения.', verbose_name='Статус суперпользователя')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
            },
        ),
    ]
