# Generated by Django 5.2 on 2026-03-09 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('scheduled_date', models.DateField(verbose_name='Дата назначения')),
                ('scheduled_time', models.TimeField(verbose_name='Время назначения')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('CONFIRMED', 'Подтвержден'), ('ASSIGNED', 'Назначен'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], db_index=True, default='NEW', max_length=20, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Код заказа')),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный менеджер')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_order', models.CharField(blank=True, help_text='Например: cleaner, senior_cleaner, helper', max_length=100, verbose_name='Роль в заказе')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_orders', to='employees.employee', verbose_name='Сотрудник')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_employees', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Назначение сотрудника',
                'verbose_name_plural': 'Назначения сотрудников',
                'ordering': ['-assigned_at'],
                'unique_together': {('order', 'employee')},
            },
        ),
    ]
