# Generated by Django 5.2 on 2025-09-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Код заказа')),
                ('category', models.CharField(choices=[('NEW', 'Новый'), ('REPEATED', 'Повторный')], max_length=50, verbose_name='Категория заказа')),
                ('service_type', models.CharField(max_length=100, verbose_name='Тип услуги')),
                ('address', models.TextField(verbose_name='Адрес выполнения')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время уборки')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Предварительная стоимость')),
                ('estimated_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Предварительный метраж (м²)')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая стоимость')),
                ('final_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговый метраж (м²)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки клиента')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('ACCEPTED', 'Принято'), ('DECLINED', 'Отклонено'), ('ASSIGNED', 'Назначено'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершено')], default='NEW', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleaners', models.ManyToManyField(blank=True, related_name='orders_cleaners', to=settings.AUTH_USER_MODEL, verbose_name='Клинеры')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_operator', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('senior_cleaner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_senior', to=settings.AUTH_USER_MODEL, verbose_name='Старший клинер')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание задачи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='orders/tasks/', verbose_name='Фото до')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='orders/tasks/', verbose_name='Фото после')),
                ('cleaner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
