# Generated by Django 5.2 on 2026-03-09 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderemployee',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения'),
        ),
        migrations.AddField(
            model_name='orderemployee',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения работы'),
        ),
        migrations.AddField(
            model_name='orderemployee',
            name='notes',
            field=models.TextField(blank=True, help_text='Внутренние заметки сотрудника о заказе', verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='orderemployee',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала работы'),
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='orders/photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_type', models.CharField(choices=[('BEFORE', 'До'), ('AFTER', 'После')], default='BEFORE', max_length=20, verbose_name='Тип фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('comment', models.TextField(blank=True, help_text='Описание или комментарий к фото', verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.order', verbose_name='Заказ')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_order_photos', to='employees.employee', verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Фото заказа',
                'verbose_name_plural': 'Фотографии заказов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
