# Generated by Django 5.2 on 2025-09-26 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'id'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Канал привлечения'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обращения'),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок выполнения'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Обычный'), ('URGENT', 'Срочный')], default='NORMAL', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник обращения'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_manager',
            field=models.CharField(blank=True, choices=[('ASSIGNED', 'Назначен'), ('COMPLETED', 'Завершён'), ('REVISION', 'Переделка'), ('DECLINED', 'Отклонено менеджером')], max_length=20, null=True, verbose_name='Статус (менеджер)'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_operator',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Принято'), ('DECLINED', 'Отклонено оператором')], max_length=20, null=True, verbose_name='Статус (оператор)'),
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий по задаче'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Назначено'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Готово')], default='ASSIGNED', max_length=20, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Предварительный метраж / объём'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговый метраж / объём'),
        ),
    ]
