# Generated by Django 5.2 on 2026-03-09 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderemployee_confirmed_at_orderemployee_finished_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_closed_at',
            field=models.DateTimeField(blank=True, help_text='Когда менеджер закрыл заказ со своей стороны', null=True, verbose_name='Закрыт менеджером (дата)'),
        ),
        migrations.AddField(
            model_name='order',
            name='operator_closed_at',
            field=models.DateTimeField(blank=True, help_text='Когда оператор закрыл заказ со своей стороны', null=True, verbose_name='Закрыт оператором (дата)'),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_review_at',
            field=models.DateTimeField(blank=True, help_text='Когда Senior Cleaner передал заказ менеджеру для проверки', null=True, verbose_name='Готов к проверке (дата)'),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_marked_ready', to=settings.AUTH_USER_MODEL, verbose_name='Готов к проверке (кто)'),
        ),
    ]
