# Generated by Django 5.2 on 2026-03-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_manager_closed_at_order_operator_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefuseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_refuses', models.PositiveIntegerField(default=3, help_text='Максимальное количество отказов за период', verbose_name='Максимум отказов')),
                ('period_days', models.PositiveIntegerField(default=14, help_text='Период в днях для подсчета отказов', verbose_name='Период (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refuse Settings',
                'verbose_name_plural': 'Refuse Settings',
            },
        ),
        migrations.AddField(
            model_name='orderemployee',
            name='refuse_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='orderemployee',
            name='refused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отказа'),
        ),
    ]
