# Generated by Django 5.2 on 2025-10-01 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_services_description'),
        ('orders', '0003_alter_task_options_remove_order_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cms.services', verbose_name='Услуга'),
        ),
    ]
