# Generated by Django 5.2 on 2025-10-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_service_type_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(blank=True, choices=[('WEBSITE', 'Сайт'), ('INSTAGRAM', 'Instagram'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('PHONE', 'Звонок'), ('REFERRAL', 'Рекомендация'), ('ADS', 'Реклама'), ('OTHER', 'Другое')], max_length=20, null=True, verbose_name='Канал привлечения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, choices=[('WEBSITE_FORM', 'Форма на сайте'), ('WEBSITE_CHAT', 'Чат на сайте'), ('INSTAGRAM_DM', 'Instagram Direct'), ('INSTAGRAM_BIO', 'Ссылка в профиле'), ('TELEGRAM_BOT', 'Telegram-бот'), ('TELEGRAM_DM', 'Личные сообщения Telegram'), ('WHATSAPP_CHAT', 'Чат WhatsApp'), ('PHONE_CALL', 'Телефонный звонок'), ('REFERRAL_FRIEND', 'Рекомендация (знакомые)'), ('REFERRAL_PARTNER', 'Рекомендация (партнёры)'), ('GOOGLE_ADS', 'Google Ads'), ('YANDEX_ADS', 'Яндекс Реклама'), ('SOCIAL_ADS', 'Реклама в соцсетях'), ('OTHER', 'Другое')], max_length=30, null=True, verbose_name='Источник обращения'),
        ),
    ]
