# Generated by Django 5.2 on 2026-03-11 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_refusesettings_orderemployee_refuse_reason_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='after_renovation',
            field=models.BooleanField(default=False, verbose_name='После ремонта'),
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Площадь (м²)'),
        ),
        migrations.AddField(
            model_name='order',
            name='bathrooms_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество санузлов'),
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('REGULAR', 'Обычная уборка'), ('DEEP', 'Генеральная уборка'), ('POST_CONSTRUCTION', 'Послеремонтная'), ('OFFICE', 'Офис'), ('WINDOWS', 'Мойка окон'), ('OTHER', 'Другое')], default='REGULAR', max_length=30, verbose_name='Категория заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='lead_channel',
            field=models.CharField(blank=True, choices=[('PHONE', 'Телефон'), ('WEBSITE', 'Сайт'), ('INSTAGRAM', 'Instagram'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('REFERRAL', 'Рекомендация'), ('OTHER', 'Другое')], default='PHONE', max_length=20, verbose_name='Канал привлечения'),
        ),
        migrations.AddField(
            model_name='order',
            name='preliminary_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Предварительная стоимость'),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Низкий'), ('NORMAL', 'Обычный'), ('HIGH', 'Высокий'), ('URGENT', 'Срочный')], default='NORMAL', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='order',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Квартира'), ('HOUSE', 'Дом'), ('OFFICE', 'Офис'), ('COMMERCIAL', 'Коммерческое'), ('OTHER', 'Другое')], default='APARTMENT', max_length=30, verbose_name='Тип помещения'),
        ),
        migrations.AddField(
            model_name='order',
            name='rooms_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество комнат'),
        ),
        migrations.AddField(
            model_name='order',
            name='windows_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество окон'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_scope',
            field=models.TextField(blank=True, help_text='Описание объёма работ', verbose_name='Объём работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.service', verbose_name='Услуга'),
        ),
    ]
