# Generated by Django 5.2 on 2025-10-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_channel_alter_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_operator',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'В обработке'), ('ACCEPTED', 'Принято'), ('DECLINED', 'Отклонено оператором')], default='IN_PROGRESS', max_length=20, null=True, verbose_name='Статус (оператор)'),
        ),
    ]
