# Generated by Django 5.2 on 2026-03-11 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_after_renovation_order_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handed_to_manager',
            field=models.BooleanField(default=False, help_text='Галочка - передано менеджеру, пусто - не передано', verbose_name='Передано менеджеру'),
        ),
        migrations.AddField(
            model_name='order',
            name='handed_to_manager_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата передачи менеджеру'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager_status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20, verbose_name='Статус (менеджер)'),
        ),
        migrations.AddField(
            model_name='order',
            name='operator_status',
            field=models.CharField(choices=[('PROCESSING', 'В обработке'), ('CONFIRMED', 'Подтверждено'), ('CANCELLED', 'Отменено')], default='PROCESSING', max_length=20, verbose_name='Статус (оператор)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('REPEAT', 'Повторный заказ')], default='NEW', max_length=30, verbose_name='Категория заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='property_type',
            field=models.CharField(choices=[('NOT_SPECIFIED', 'Не указан'), ('APARTMENT', 'Квартира'), ('HOUSE', 'Дом'), ('LAND', 'Земельный участок'), ('BUSINESS', 'Бизнес помещение'), ('OFFICE', 'Офис'), ('OTHER', 'Другое')], default='NOT_SPECIFIED', max_length=30, verbose_name='Тип помещения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_scope',
            field=models.TextField(blank=True, help_text='Пример: 50м², 2 комнаты, кухня', verbose_name='Объём работы'),
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('comment', models.TextField(blank=True, help_text='Описание файла', verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.order', verbose_name='Заказ')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Вложение заказа',
                'verbose_name_plural': 'Вложения заказа',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
