# Generated by Django 5.2 on 2026-03-11 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_handed_to_manager_order_handed_to_manager_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transferred_to_manager',
            field=models.BooleanField(default=False, help_text='Оператор передал заказ менеджеру для обработки', verbose_name='Передан менеджеру'),
        ),
        migrations.AddField(
            model_name='order',
            name='transferred_to_manager_at',
            field=models.DateTimeField(blank=True, help_text='Когда оператор передал заказ менеджеру', null=True, verbose_name='Передан менеджеру (дата)'),
        ),
        migrations.AddField(
            model_name='order',
            name='transferred_to_manager_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_transferred_to_manager', to=settings.AUTH_USER_MODEL, verbose_name='Передан менеджеру (кем)'),
        ),
    ]
