# Generated by Django 5.2 on 2025-10-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_manager',
            field=models.CharField(blank=True, choices=[('ASSIGNED', 'Назначен'), ('IN_PROGRESS', 'В работе'), ('CHECKING', 'На проверке'), ('COMPLETED', 'Завершён'), ('REVISION', 'Переделка'), ('DECLINED', 'Отклонено менеджером')], max_length=20, null=True, verbose_name='Статус (менеджер)'),
        ),
    ]
