# Generated by Django 5.2 on 2025-10-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_manager',
            field=models.CharField(blank=True, choices=[('ASSIGNED', 'Назначен'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершён'), ('DECLINED', 'Отклонено')], max_length=20, null=True, verbose_name='Статус (менеджер)'),
        ),
    ]
