# Generated by Django 5.2 on 2026-03-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_transferred_to_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='senior_cleaner_status',
            field=models.CharField(choices=[('WAITING', 'В ожидании'), ('ACCEPTED', 'Принял'), ('WORKING', 'В работе'), ('SENT_FOR_REVIEW', 'Отправлено на проверку')], default='WAITING', max_length=20, verbose_name='Статус старшего клинера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager_status',
            field=models.CharField(choices=[('WAITING', 'В ожидании'), ('IN_PROGRESS', 'В обработке'), ('PROCESS', 'В процессе'), ('REVIEW', 'В проверке'), ('DELIVERED', 'Сдано')], default='WAITING', max_length=20, verbose_name='Статус менеджера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operator_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'В обработке'), ('TRANSFERRED', 'Передано'), ('REJECTED', 'Отклонено'), ('SUCCESS', 'Успешно')], default='IN_PROGRESS', max_length=20, verbose_name='Статус оператора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'В обработке'), ('IN_WORK', 'В работе'), ('ON_REVIEW', 'На проверке'), ('CANCELLED', 'Отклонён'), ('COMPLETED', 'Успешно завершён')], db_index=True, default='PROCESSING', max_length=20, verbose_name='Статус'),
        ),
    ]
