# Generated by Django 5.2 on 2025-10-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'В работе'), ('DONE', 'Готово')], default='IN_PROGRESS', max_length=20, verbose_name='Статус задачи'),
        ),
    ]
