# Generated by Django 5.2 on 2026-03-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_senior_cleaner_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес выполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(verbose_name='Дата уборки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_time',
            field=models.TimeField(verbose_name='Время уборки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'В обработке'), ('IN_WORK', 'В работе'), ('ON_REVIEW', 'На проверке'), ('CANCELLED', 'Отклонён'), ('COMPLETED', 'Успешно завершён')], db_index=True, default='PROCESSING', help_text='Главный статус (рассчитывается автоматически)', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
