# Generated by Django 5.2 on 2025-10-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quality_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий по качеству'),
        ),
        migrations.AddField(
            model_name='order',
            name='quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оценка от 1 до 5 звёзд', null=True, verbose_name='Оценка качества (1-5)'),
        ),
        migrations.AddField(
            model_name='order',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='order',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Проверил (менеджер)'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Работа завершена'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Работа начата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_manager',
            field=models.CharField(blank=True, choices=[('ASSIGNED', 'Назначен'), ('IN_PROGRESS', 'В работе'), ('PENDING_REVIEW', 'На проверке'), ('COMPLETED', 'Завершён'), ('DECLINED', 'Отклонено')], max_length=20, null=True, verbose_name='Статус (менеджер)'),
        ),
    ]
