# Generated by Django 5.2 on 2026-03-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_address_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agreed_services',
            field=models.TextField(blank=True, help_text='Точный перечень работ и услуг по договорённости', verbose_name='Согласованные услуги'),
        ),
        migrations.AddField(
            model_name='order',
            name='completion_deadline',
            field=models.DateField(blank=True, help_text='Крайняя дата завершения работы', null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_details',
            field=models.TextField(blank=True, help_text='Особые условия, гарантии, дополнительные соглашения', verbose_name='Детали договора'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_number',
            field=models.CharField(blank=True, help_text='Номер подписанного договора', max_length=50, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='order',
            name='meeting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата встречи'),
        ),
        migrations.AddField(
            model_name='order',
            name='meeting_notes',
            field=models.TextField(blank=True, help_text='Важная информация с офлайн встречи с клиентом', verbose_name='Заметки со встречи'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Наличные'), ('TRANSFER', 'Перечисление'), ('CARD', 'Банковская карта'), ('ONLINE', 'Онлайн оплата')], max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('PREPAY', 'Предоплата 100%'), ('PREPAY_50', 'Предоплата 50%'), ('POSTPAY', 'Постоплата'), ('STAGE', 'Поэтапная оплата')], max_length=20, null=True, verbose_name='Условия оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='special_conditions',
            field=models.TextField(blank=True, help_text='Скидки, акции, дополнительные договорённости', verbose_name='Особые условия'),
        ),
    ]
