# Generated by Django 5.2 on 2026-03-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_agreed_services_order_completion_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='agreed_services',
        ),
        migrations.RemoveField(
            model_name='order',
            name='completion_deadline',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contract_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meeting_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meeting_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_conditions',
        ),
        migrations.AddField(
            model_name='order',
            name='prepayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Указывается оператором при создании заказа', max_digits=10, verbose_name='Сумма предоплаты'),
        ),
    ]
