# Generated by Django 5.2 on 2025-10-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_quality_comment_order_quality_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='property_type',
            field=models.CharField(blank=True, choices=[('APARTMENT', 'Квартира'), ('HOUSE', 'Дом'), ('LAND', 'Земельный участок'), ('BUSINESS', 'Бизнес помещение'), ('OFFICE', 'Офис'), ('OTHER', 'Другое')], max_length=20, null=True, verbose_name='Тип помещения'),
        ),
    ]
