# Generated by Django 5.2 on 2026-03-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_agreed_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manager_status',
            field=models.CharField(choices=[('WAITING', 'В ожидании'), ('IN_PROGRESS', 'В обработке'), ('PROCESS', 'В процессе'), ('REVIEW', 'В проверке'), ('DELIVERED', 'Сдано'), ('REJECTED', 'Отклонено')], default='WAITING', max_length=20, verbose_name='Статус менеджера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='senior_cleaner_status',
            field=models.CharField(choices=[('WAITING', 'В ожидании'), ('ACCEPTED', 'Принял'), ('WORKING', 'В работе'), ('SENT_FOR_REVIEW', 'Отправлено на проверку'), ('REJECTED', 'Отклонено')], default='WAITING', max_length=20, verbose_name='Статус старшего клинера'),
        ),
    ]
