# Generated by Django 5.2 on 2025-10-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Предварительная стоимость'),
        ),
    ]
