# Generated by Django 5.2 on 2025-11-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='decline_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='senior_cleaner_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий старшего клинера'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_senior_cleaner',
            field=models.CharField(blank=True, choices=[('ASSIGNED', 'Назначен'), ('ACCEPTED', 'Принят'), ('IN_PROGRESS', 'В работе'), ('PENDING_REVIEW', 'На проверке менеджера'), ('COMPLETED', 'Завершён'), ('DECLINED', 'Отказался')], default='ASSIGNED', max_length=20, null=True, verbose_name='Статус (старший клинер)'),
        ),
    ]
