# Generated by Django 5.2 on 2026-03-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_item_type'),
        ('orders', '0012_alter_order_manager_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInventoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Использованное количество')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_usages', to='inventory.inventoryitem', verbose_name='Инвентарь')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_usages', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Использование инвентаря в заказе',
                'verbose_name_plural': 'Использование инвентаря в заказах',
                'ordering': ['inventory_item__item_type', 'inventory_item__category__name', 'inventory_item__name'],
                'unique_together': {('order', 'inventory_item')},
            },
        ),
    ]
