# Generated by Django 5.2 on 2025-11-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_decline_reason_order_senior_cleaner_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_area',
            field=models.PositiveIntegerField(blank=True, help_text='Площадь в м², количество комнат, окон и т.д.', null=True, verbose_name='Объём работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_area',
            field=models.PositiveIntegerField(blank=True, help_text='Площадь в м², количество комнат, окон и т.д.', null=True, verbose_name='Фактический объём работы'),
        ),
    ]
