# Generated by Django 5.2 on 2025-11-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_estimated_area_alter_order_final_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_area',
            field=models.CharField(blank=True, help_text='Например: 50 м², 3 комнаты, 5 окон', max_length=100, null=True, verbose_name='Объём работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_area',
            field=models.CharField(blank=True, help_text='Например: 50 м², 3 комнаты, 5 окон', max_length=100, null=True, verbose_name='Фактический объём работы'),
        ),
    ]
