# Generated by Django 5.2 on 2025-12-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_estimated_area_alter_order_final_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'В работе'), ('PENDING_REVIEW', 'На проверке'), ('DONE', 'Готово')], default='IN_PROGRESS', max_length=20, verbose_name='Статус задачи'),
        ),
    ]
