# Generated by Django 5.2 on 2025-12-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cleaners',
        ),
        migrations.RemoveField(
            model_name='order',
            name='decline_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='senior_cleaner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='senior_cleaner_comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_senior_cleaner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='cleaner',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'В работе'), ('DONE', 'Готово')], default='IN_PROGRESS', max_length=20, verbose_name='Статус задачи'),
        ),
    ]
