# Generated by Cascade on 2025-12-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_order_cleaners_remove_order_decline_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='senior_cleaner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders_senior_cleaner',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Старший клинер',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='cleaners',
            field=models.ManyToManyField(
                blank=True,
                related_name='orders_cleaners',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Клинеры',
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='task',
                    name='cleaner',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='tasks_cleaner',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Клинер',
                    ),
                ),
            ],
        ),
    ]
