# Generated by Cascade

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_restore_cleaners_and_task_cleaner"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="after_repair",
            field=models.BooleanField(default=False, verbose_name="После ремонта"),
        ),
        migrations.AddField(
            model_name="order",
            name="bathrooms_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Санузлы (кол-во)"),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_rooms",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Комнаты (предв.)"),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_sqm",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Площадь м² (предв.)"),
        ),
        migrations.AddField(
            model_name="order",
            name="windows_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Окна (кол-во)"),
        ),
    ]
