# Generated by Django 5.2 on 2026-03-09 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CHEMICALS', 'Химия'), ('TRANSPORT', 'Транспорт'), ('TOOLS', 'Инструменты'), ('CONSUMABLES', 'Расходники'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='expenses/', verbose_name='Фото чека')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата расхода')),
                ('status', models.CharField(choices=[('PENDING', 'На проверке'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='employees.employee', verbose_name='Сотрудник')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-created_at'],
            },
        ),
    ]
