# Generated by Django 5.2 on 2026-03-19 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_avatar'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_general',
            field=models.BooleanField(default=False, help_text='Общие расходы компании (аренда, химия и т.д.)', verbose_name='Общий расход'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('CHEMICALS', 'Химия'), ('TRANSPORT', 'Транспорт'), ('TOOLS', 'Инструменты'), ('CONSUMABLES', 'Расходники'), ('RENT', 'Аренда'), ('UTILITIES', 'Коммунальные услуги'), ('OFFICE', 'Офисные расходы'), ('MARKETING', 'Маркетинг'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='employees.employee', verbose_name='Сотрудник'),
        ),
    ]
