# Generated by Django 5.2 on 2026-03-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_is_general_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
    ]
