# Generated by Django 5.2 on 2026-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_employee_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ORDER', 'По заказам'), ('CHEMICALS', 'Химия'), ('TRANSPORT', 'Транспорт'), ('TOOLS', 'Инструменты'), ('CONSUMABLES', 'Расходники'), ('RENT', 'Аренда'), ('UTILITIES', 'Коммунальные услуги'), ('OFFICE', 'Офисные расходы'), ('MARKETING', 'Маркетинг'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Категория'),
        ),
    ]
