# Generated by Django 6.0.3 on 2026-04-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('CHEMICALS', 'Химия'), ('TRANSPORT', 'Транспорт'), ('TOOLS', 'Инструменты'), ('CONSUMABLES', 'Расходники'), ('RENT', 'Аренда'), ('UTILITIES', 'Коммунальные услуги'), ('OFFICE', 'Офисные расходы'), ('MARKETING', 'Маркетинг'), ('LUNCH', 'Обед'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Категория'),
        ),
    ]
