# Generated by Django 5.2 on 2025-10-01 06:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание Услуги'),
        ),
    ]
