# Generated by Django 5.2 on 2025-10-15 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_services_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['order'], 'verbose_name': '2) Услуги', 'verbose_name_plural': '2) Услуги'},
        ),
        migrations.CreateModel(
            name='ServiceTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание задачи')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок выполнения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='cms.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Шаблон задачи для услуги',
                'verbose_name_plural': 'Шаблоны задач для услуг',
                'ordering': ['service', 'order'],
            },
        ),
    ]
