# Generated by Cascade

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_alter_services_options_servicetasktemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="description",
        ),
        migrations.RemoveField(
            model_name="services",
            name="image",
        ),
    ]
