# Generated by Cascade

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_remove_services_description_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="price",
        ),
    ]
