# Generated by Django 5.2 on 2026-03-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Только одна запись должна быть активной', verbose_name='Активно')),
                ('bot_token', models.CharField(blank=True, help_text='Токен Telegram бота от @BotFather', max_length=255, verbose_name='Токен бота')),
                ('group_chat_id', models.CharField(blank=True, help_text='ID Telegram группы или чата для уведомлений', max_length=100, verbose_name='ID группы/чата')),
                ('notifications_new_order', models.BooleanField(default=True, help_text='Отправлять уведомление при создании заказа', verbose_name='Новый заказ')),
                ('notifications_new_expense', models.BooleanField(default=True, help_text='Отправлять уведомление при создании расхода', verbose_name='Новый расход')),
                ('notifications_expense_approved', models.BooleanField(default=True, help_text='Отправлять уведомление при одобрении расхода', verbose_name='Расход одобрен')),
                ('notifications_expense_rejected', models.BooleanField(default=True, help_text='Отправлять уведомление при отклонении расхода', verbose_name='Расход отклонен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки Telegram',
                'verbose_name_plural': 'Настройки Telegram',
            },
        ),
    ]
