# Generated by Django 5.2 on 2026-03-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Бот будет обрабатывать сообщения только если активен', verbose_name='Активно')),
                ('bot_token', models.CharField(blank=True, help_text='Токен Telegram бота для клиентов от @BotFather', max_length=255, verbose_name='Токен бота')),
                ('bot_username', models.CharField(blank=True, help_text='Например: @KikiClientBot', max_length=255, verbose_name='Username бота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки бота для клиентов',
                'verbose_name_plural': 'Настройки бота для клиентов',
            },
        ),
    ]
