# Generated by Django 5.2 on 2025-11-03 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram пользователь', 'verbose_name_plural': 'Telegram пользователи'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы'),
        ),
    ]
