# Generated by Django 5.2 on 2026-03-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_clientbotsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramsettings',
            old_name='group_chat_id',
            new_name='chat_id',
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='alerts_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для алертов и отказов', max_length=100, verbose_name='ID темы алертов'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='cleaner_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для событий клинеров', max_length=100, verbose_name='ID темы событий клинеров'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='completed_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для завершённых заказов', max_length=100, verbose_name='ID темы завершённых заказов'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='expenses_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для расходов', max_length=100, verbose_name='ID темы расходов'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='orders_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для заказов', max_length=100, verbose_name='ID темы заказов'),
        ),
    ]
