# Generated by Django 5.2 on 2026-03-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_telegramsettings_status_changes_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsettings',
            name='cleaner_thread_id',
            field=models.CharField(blank=True, help_text='ID темы Telegram для всех уведомлений системы (статусы, назначения, клинеры)', max_length=100, verbose_name='Уведомления'),
        ),
    ]
