version: '3.8'

services:
  db_kikicrm:
    image: postgres:14
    container_name: postgres_db_kikicrm
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data_kikicrm:/var/lib/postgresql/data
    networks:
      - portfolio_network_kikicrm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_kikicrm:
    image: redis:6
    container_name: redis_kikicrm
    restart: always
    networks:
      - portfolio_network_kikicrm

  web_kikicrm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_kikicrm
    restart: always
    command: sh -c "/entrypoint.sh && gunicorn core.wsgi:application --bind 0.0.0.0:8001"
    volumes:
      - ../app:/app
      - ../app/core/staticfiles:/app/core/staticfiles
      - ../app/media:/app/media
    env_file:
      - /root/KIKICRM/.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      db_kikicrm:
        condition: service_healthy
      redis_kikicrm:
        condition: service_started
    ports:
      - "8001:8001"
    networks:
      - portfolio_network_kikicrm

  telegram_bot_kikicrm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram_bot_kikicrm
    restart: always
    command: python manage.py bot
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    depends_on:
      - db_kikicrm
      - web_kikicrm
    networks:
      - portfolio_network_kikicrm

networks:
  portfolio_network_kikicrm:
    driver: bridge

volumes:
  postgres_data_kikicrm:
