# Generated by Django 5.2 on 2026-03-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, help_text='Уникальный код сотрудника (можно назначить позже)', max_length=20, null=True, unique=True, verbose_name='Код сотрудника')),
                ('phone_secondary', models.CharField(blank=True, default='', help_text='Второй номер телефона для связи', max_length=20, verbose_name='Дополнительный телефон')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('INACTIVE', 'Неактивен'), ('ON_LEAVE', 'В отпуске'), ('FIRED', 'Уволен'), ('CANDIDATE', 'Кандидат')], db_index=True, default='CANDIDATE', max_length=20, verbose_name='Статус')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приема')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('notes', models.TextField(blank=True, default='', help_text='Внутние заметки о сотруднике', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-created_at'],
            },
        ),
    ]
