# Generated by Cascade on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('orders', '0012_alter_order_manager_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_order', models.CharField(blank=True, max_length=100, verbose_name='Роль в заказе')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('earned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата начисления')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='Оплачено')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='employees.employee', verbose_name='Сотрудник')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_earnings', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Начисление сотруднику',
                'verbose_name_plural': 'Начисления сотрудникам',
                'ordering': ['-earned_at'],
                'unique_together': {('employee', 'order')},
            },
        ),
    ]
