# Generated by Django 6.0.3 on 2026-04-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_deactivation_reason_employee_firing_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Срок найма/окончания договора', null=True, verbose_name='Дата окончания контракта'),
        ),
    ]
