# Generated by Django 6.0.3 on 2026-04-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_contract_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_term',
            field=models.IntegerField(blank=True, choices=[(3, '3 месяца'), (6, '6 месяцев'), (12, '1 год')], help_text='Срок действия договора в месяцах', null=True, verbose_name='Срок найма'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Автоматически рассчитывается на основе даты приема и срока найма', null=True, verbose_name='Дата окончания контракта'),
        ),
    ]
