# Generated by Django 6.0.3 on 2026-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_contract_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_file',
            field=models.FileField(blank=True, help_text='Загрузите скан или фото договора', null=True, upload_to='employees/contracts/', verbose_name='Файл договора'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания срока'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issued_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_type',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Паспорт'), ('ID_CARD', 'ID карта'), ('CERTIFICATE', 'Свидетельство'), ('OTHER', 'Другой документ')], default='PASSPORT', max_length=20, verbose_name='Тип документа'),
        ),
    ]
