# Generated by Django 5.2 on 2026-03-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='service',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='Список задач которые выполняются в рамках услуги', verbose_name='Чеклист задач'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фото услуги'),
        ),
    ]
