# Generated by Cascade on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_extraservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cleaner_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ЗП клинеру'),
        ),
        migrations.AddField(
            model_name='service',
            name='senior_cleaner_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ЗП ст. клинеру'),
        ),
    ]
