# Generated by Cascade on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_senior_cleaner_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_deadline_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дедлайн услуги (часы)'),
        ),
    ]
