# Generated by Django 5.2 on 2026-03-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('services', '0006_service_service_deadline_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='inventory_items',
            field=models.ManyToManyField(blank=True, help_text='Инструменты и материалы, используемые для этой услуги', related_name='services', to='inventory.inventoryitem', verbose_name='Инвентарь'),
        ),
    ]
