# Generated by Django 5.2 on 2026-03-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_item_type'),
        ('services', '0007_service_inventory_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='inventory_items',
        ),
        migrations.CreateModel(
            name='ServiceInventoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Рекомендуемое количество')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_templates', to='inventory.inventoryitem', verbose_name='Инвентарь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_templates', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Шаблон инвентаря услуги',
                'verbose_name_plural': 'Шаблоны инвентаря услуг',
                'ordering': ['inventory_item__item_type', 'inventory_item__name'],
                'unique_together': {('service', 'inventory_item')},
            },
        ),
    ]
