# Generated by Django 5.2 on 2026-03-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дополнительный телефон')),
                ('source', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Сайт'), ('RECOMMENDATION', 'Рекомендация'), ('ADS', 'Реклама'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Источник')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
