# Generated by Django 5.2 on 2026-03-10 22:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('company', 'Компания'), ('vip', 'VIP')], default='individual', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unspecified', 'Не указан')], default='unspecified', max_length=15, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.CharField(blank=True, max_length=255, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?[\\d\\s\\-\\(\\)]+$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?[\\d\\s\\-\\(\\)]+$')], verbose_name='Дополнительный телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Оценка клиента от 1 до 10', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('website', 'Сайт'), ('instagram', 'Instagram'), ('referral', 'Рекомендация'), ('other', 'Другое')], default='website', max_length=20, verbose_name='Источник'),
        ),
    ]
