# Generated by Django 5.2 on 2025-09-22 13:22

import apps.clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, validators=[apps.clients.models.validate_phone_number], verbose_name='Телефон'),
        ),
    ]
