# Generated by Django 5.2 on 2025-09-21 21:18

import apps.clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='client',
            name='_whatsapp_number',
            field=models.CharField(blank=True, db_column='whatsapp_number', help_text='Введите номер телефона в международном формате (например: 77001234567)', max_length=20, null=True, validators=[apps.clients.models.Client.validate_whatsapp_number], verbose_name='WhatsApp номер'),
        ),
    ]
