# Generated by Django 5.2 on 2026-03-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_name_client_address_client_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='rating',
        ),
    ]
