# Generated by Django 5.2 on 2025-09-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_remove_client_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='_whatsapp_number',
            field=models.CharField(blank=True, db_column='whatsapp_number', help_text='Введите номер телефона в международном формате (например: 555123456 или 0555123456)', max_length=20, null=True, verbose_name='WhatsApp номер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
