# Generated by Django 5.2 on 2025-09-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client__whatsapp_number_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, help_text='Уникальный 5-значный идентификатор клиента', max_length=5, unique=True, verbose_name='ID клиента'),
        ),
    ]
