# Generated by Django 5.2 on 2026-03-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заметка клиента',
                'verbose_name_plural': 'Заметки клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
