# Generated by Django 5.2 on 2025-09-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client__whatsapp_number_alter_client_phone'),
        ('clients', '0004_add_client_id'),
    ]

    operations = [
    ]
