# Generated by Django 5.2 on 2026-03-22 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_password', models.CharField(blank=True, default='', help_text='Пароль по умолчанию для новых клинеров', max_length=128, verbose_name='Стандартный пароль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_settings', to=settings.AUTH_USER_MODEL, verbose_name='HR пользователь')),
            ],
            options={
                'verbose_name': 'Настройки HR',
                'verbose_name_plural': 'Настройки HR',
            },
        ),
    ]
