# Generated by Django 5.2 on 2026-03-09 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('orders', '0002_orderemployee_confirmed_at_orderemployee_finished_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Химия, Инструменты, Расходники', max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Опциональное описание категории', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные категории не отображаются в списках', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория инвентаря',
                'verbose_name_plural': 'Категории инвентаря',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название товара', max_length=200, unique=True, verbose_name='Название')),
                ('unit', models.CharField(default='шт', help_text='шт, литр, мл, упаковка, кг', max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Текущий остаток на складе', max_digits=15, verbose_name='Текущее количество')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Критический минимум для алертов', max_digits=15, verbose_name='Минимальный остаток')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Закупочная цена за единицу', max_digits=12, verbose_name='Цена за единицу')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные товары скрыты из операций', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар на складе',
                'verbose_name_plural': 'Товары на складе',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Списание'), ('ADJUSTMENT', 'Корректировка')], default='IN', max_length=20, verbose_name='Тип операции')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Для списания используйте положительное число', max_digits=15, verbose_name='Количество')),
                ('comment', models.TextField(blank=True, help_text='Причина корректировки или детали операции', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('employee', models.ForeignKey(blank=True, help_text='Кто выполнил операцию или использовал товар', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='employees.employee', verbose_name='Сотрудник')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem', verbose_name='Товар')),
                ('order', models.ForeignKey(blank=True, help_text='Связанный заказ (для списаний)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Операция со складом',
                'verbose_name_plural': 'Операции со складом',
                'ordering': ['-created_at'],
            },
        ),
    ]
