# Generated by Django 5.2 on 2026-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('LARGE', 'Крупный'), ('SMALL', 'Мелкий')], db_index=True, default='SMALL', help_text='Крупный: техника и оборудование. Мелкий: расходники, тряпки, насадки и т.д.', max_length=20, verbose_name='Тип инвентаря'),
        ),
    ]
