# Generated by Django 5.2 on 2026-03-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_item_type'),
        ('orders', '0013_orderinventoryusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='usage',
            field=models.ForeignKey(blank=True, help_text='Связанная строка фактического использования инвентаря', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.orderinventoryusage', verbose_name='Строка использования'),
        ),
    ]
