# Generated by Django 5.2 on 2026-04-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0013_orderinventoryusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('POSITIVE', 'Положительный'), ('NEGATIVE', 'Отрицательный')], default='POSITIVE', max_length=20, verbose_name='Тип отзыва')),
                ('description', models.TextField(blank=True, default='', help_text='Текст отзыва или комментарий', verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, help_text='Фотография к отзыву (скриншот, фото клиента и т.д.)', null=True, upload_to='reviews/%Y/%m/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
