# Generated by Django 5.2 on 2026-03-09 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('orders', '0003_order_manager_closed_at_order_operator_closed_at_and_more'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Стандартный чеклист для генеральной уборки', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание шаблона', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_template', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Шаблон чеклиста',
                'verbose_name_plural': 'Шаблоны чеклистов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Протереть пыль, Помыть пол', max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, help_text='Детальное описание что нужно сделать', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения задач', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.checklisttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Задача в шаблоне',
                'verbose_name_plural': 'Задачи в шаблоне',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Выполнено'), ('SKIPPED', 'Пропущено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('order_position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('notes', models.TextField(blank=True, help_text='Комментарии к выполнению задачи', verbose_name='Примечания')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='employees.employee', verbose_name='Назначенный сотрудник')),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто завершил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Задача заказа',
                'verbose_name_plural': 'Задачи заказа',
                'ordering': ['order_position', 'id'],
            },
        ),
    ]
