# Generated by Django 5.2 on 2026-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('IN_PROGRESS', 'В работе'), ('ON_REVIEW', 'На проверке'), ('DONE', 'Выполнено'), ('SKIPPED', 'Пропущено')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
    ]
